### ISSUE TITLE
Configuration: Readme.md

### ISSUE THREAD

**Issue by ivasconcellos** [Ranqueei-Team/Projeto_Hackathon_TechAcademy#40]
- Imagem da licença
- Tecnologias Necessárias para utilizar o projeto
- Como executar o projeto;
- Sobre o Ranqueei
- Missão, Visão e Valores
- Nos autores colocar hiperlink para o linkedin
- Agradecimento

**Comment by rllimaferreira** [comment]
Modelos de referência:

- Instruções : https://github.com/rllimaferreira/sds1-wmazoni

**Comment by rllimaferreira** [comment]
- https://github.com/rllimaferreira/startse_tech_academy

- https://github.com/rllimaferreira/QAcademy-Selenium-Com-RobotFramework
